---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mossbyte/library.mossbyteagency.com/
    - cd "$DEPLOYPATH" && /usr/bin/touch database/database.sqlite
    - cd "$DEPLOYPATH" && composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
    - cd "$DEPLOYPATH" && php artisan migrate --force --no-interaction
    - cd "$DEPLOYPATH" && php artisan storage:link
    - cd "$DEPLOYPATH" && php artisan optimize:clear
    - cd "$DEPLOYPATH" && php artisan optimize
